- README.md
Without this package, CMake fails with the error:
Could NOT find OpenGL (missing: OPENGL_INCLUDE_DIR)
This package is listed in Qt's requirements here:
https://doc.qt.io/qt-6/linux.html#requirements-for-development-host
> Meta: Add libgl1-mesa-dev to build dependencies

- WebView.cpp
- WebView.h
On high-dpi systems QT will automatically scale up painting operations.
This results in an ugly blurry browser window surrounded by a nicely
scaled window frame. This patch applies an inverse scale to the WebView
widget, ensuring the painting and mouse events are lined up and draw
with a 1:1 pixel ratio with respect to the display's device pixels.
> Apply inverse image scaling to ensure the WebView renders at 1:1

- BrowserWindow.cpp
- BrowserWindow.h
- main.cpp
This patch adds an event handler to the main window which allows it to
respond to a user closing the window. This event is then passed on to
the LibCore event loop, which allows the application quit itself.
Previously the application would hang, only running in the background,
until killed by an external force.
> Trigger browser to quit when the main window is closed

- BrowserWindow.cpp
- BrowserWindow.h
- CMakeLists.txt
- History.cpp
- History.h
- Tab.cpp
- Tab.h
- WebView.cpp
- WebView.h
This patch removes the browser WebView from the window and places it
inside a Tab object, all wrapped up in a QT tab control.
This patch takes the browser history code from the Serenity browser and
wires it up to the QT interface. This is tied in with a few extra
toolbar buttons associated with each tab.
> Tabbed browsing support

- WebView.cpp
Set singleStep for scroll bars in WebView
- Sets singleStep to 24px, this allows you to scroll using your mouse scroll wheel :^)
Set pageStep for scroll bars in WebView
- This allows PageUp/PageDown keys to scroll 1 viewport size at a time.
- This also fixes the scroll bar drag handle to be a correct length.
> Fix scroll bar and mouse wheel scrolling

- BrowserWindow.cpp
- BrowserWindow.h
This also fixes the `- Ladybird` branding when switching between tabs.
> Hide TabBar if count <= 1

- BrowserWindow.cpp
- Tab.cpp
This gives the actual webcontent more space to work with,
it also emulates how other browsers does it.
In the future we'd like to do something else since only ToolTip
can be visible at the same time.
> Replace StatusBar with ToolTip

- .gitignore
- AndroidPlatform.cpp
- CMakeLists.txt
- README.md
- WebView.cpp
- android/AndroidManifest.xml
- android/build.gradle
- android/gradle.properties
- android/res/values/libs.xml
- android/src/org/serenityos/ladybird/TransferAssets.java
- cmake/AndroidExtras.cmake
- cmake/EnableLLD.cmake
- cmake/FetchLagom.cmake
Build an Android APK file that, when configured properly in Qt Creator,
can be used to deploy the browser to an Android device.
The current build requires NDK 33, targets no less than Android API 32,
and Qt Creator 6.4.0.
Requires https://github.com/SerenityOS/serenity/pull/14606
> Meta: Add Android build

- WebView.cpp
- WebView.h
This handles most (?) or keyboard input. For some reason "control+a" and enter are not working on google.com
It can handle plain ASCII, I tested also Hebrew input (high above in the Unicode range, see note bellow), and https://playbiolab.com/ (which is playable now!)
I am unsure about the bid ugly key conversion function... I am unsure if a hashmap would be better... Most of the keys match 1:1 to Qt... but there are some minor differences. 
Note about BIDI:
The web rendering engine does not handle BIDI, KJC nor hindic, any complex text layout is not working now, I assume someone will code it in the next 10 years :)
> Basic keyboard input

- BrowserWindow.cpp
- BrowserWindow.h
This PR adds the capability to close the current tab by
pressing Ctrl-W. If there is only one tab open, the browser
window will close.
> Add Ctrl-W action to close current tab

- Tab.cpp
- Tab.h
When a http(s):// is not written by the user - lets manually add one.
(PS: why is gemini support missing from the library?)
> Add a protocol to the URL, when one is not set

- BrowserWindow.cpp
- CMakeLists.txt
- Settings.cpp
- Settings.h
- SettingsDialog.cpp
- SettingsDialog.h
- Tab.cpp
- main.cpp
This also adds a `Settings` class that can be extended in the future (eg #20 could take advantage of it to let the user decide which search-provider they'd like to use). :^)
> Add SettingsDialog

- Info.plist
This also adds an Info.plist file required to properly
build macOS applications.
> Meta: Enable macOS high-dpi support

- Info.plist
I think the recommended approach to bundle identifier is using reverse domain name notation.
This PR should be reviewed by @filiphsps before merged.
> Meta: use reverse domain name notation in property list files

- CMakeLists.txt
In the future, ladybird should probably use a QOpenGLWidget or similar platform plugin to use the native GL implementation instead of the one in serenity.
Requires: https://github.com/SerenityOS/serenity/pull/15260
Fixes #16
> CMake: Link against LibSoftGPU to enable WebGL using serenity LibGL

- CMakeLists.txt
- WebView.cpp
- cmake/InstallRules.cmake
- cmake/LadybirdInstallConfig.cmake
This setup should allow the package maintainers who are looking to
distribute ladybird on their distributions to use CMake to install
ladybird using cmake install rules rather than having to write their own
Requires https://github.com/SerenityOS/serenity/pull/15257
Fixes #36
> CMake: Install resources and Lagom libraries alongside ladybird 

- Tab.cpp
This commit changes how we set the back and forward button key bindings
to use platform-specific standard key sequences.
For example, in Mac OS X, the back action will be now triggered via
Cmd+← and Cmd+[, whereas previously the action was mapped to Alt+←,
which is not standard in Mac OS X.
> Tab: Make back/forward keyboard shortcuts platform-specific

- .github/workflows/ci.yml
Let's verify that things at least build on pushes to master, and in PRs.
A few succesful CI runs from my fork showing the ccache working:
No ccache: https://github.com/ADKaster/ladybird/actions/runs/3075281272
Yes ccache: https://github.com/ADKaster/ladybird/actions/runs/3075390659
Creating UCD/CLDR/TZDB caches: https://github.com/ADKaster/ladybird/actions/runs/3078277536/jobs/4973731841
Full UCD/CLDR/TZDB caches: https://github.com/ADKaster/ladybird/actions/runs/3078478190
> Meta: Add basic GitHub Actions workflow for ubuntu/macOS builds

- README.md
This option enables pacman to skip already installed packages instead of reinstalling them.
It's also present in the main [Serenity OS build instructions](https://github.com/SerenityOS/serenity/blob/master/Documentation/BuildInstructions.md#arch-linux--manjaro).
> README: Add --needed option on pacman dependencies command

- WebView.cpp
There are a lot of unsupported mouse click events that the engine
cannot handle. It such event (`0`) reaches the web engine - it will
assert.
Don't even propagate them - this is the safe way. As of today!
I also added back/forward buttons to the translation.
NOTE that I removed one button related function. I am under assumption
that we always need to send a bitmask. I may be wrong... in such
case - I will revert part of this PR.
Should fix #27
> Don't propagate unrecognized button clicks to the web engine

- PageClientLadybird.cpp
- PageClientLadybird.h
- WebView.cpp
- WebView.h
This requires the SerenityOS PR: https://github.com/SerenityOS/serenity/issues/15308
> WebView: Ensure there is a console widget when storing console messages and initialize console earlier

- Tab.cpp
- Tab.h
This should be safer than using `QMainWindow` and `reinterpret_cast`. I assume there was a reason for using QMainWindow though, if there was, please let me know and close this PR.
> Make Tab.cpp directly take a BrowserWindows as m_window

- BrowserWindow.cpp
- Settings.cpp
- Settings.h
- SettingsDialog.cpp
- SimpleWebView.cpp
- Tab.cpp
- main.cpp
This prevents memory leaks detected by both Valgrind and ASAN/LSAN.
Valgrind is still suspicious of the leaked JS::VM from Web::Bindings::main_thread_vm() but there's other issues with leak checking all the GC'd objects.
Co-Authored-By: Diego Iastrubni <diegoiast@gmail.com>
Supersedes #80
> Everywhere: Ensure that Qt objects are created with parents

- BrowserWindow.cpp
View Source was a subwindow that made it cover part of the browser with no way for closing it.
Was:
Now:
Note that this doesn't change the fact that the View Source window is still a child of the Browser Window.
> BrowserWindow: Make "View Source" a separate window

- SimpleWebView.cpp
`size()` may include the dimensions of the scrollbars. We now use `viewport()` instead.
> WebView: Fix size calculation in update_viewport_rect()

- ConsoleClient.cpp
- ConsoleClient.h
This matches the changes made to Serenity in:
https://github.com/SerenityOS/serenity/commit/7a2da4cabf5627941cf1fc6eb7c5fd068fcc75f9
> ConsoleClient: Implement console message styling with `%c`

- CMakeLists.txt
This causes CMake to output a WebContent build, without this it would not build WebContent and Ladybird would be unusable since it couldn't find the WebContent executable.
> Make ladybird depend on WebContent

- CMakeLists.txt
- WebContent/CMakeLists.txt
- WebContent/main.cpp
- WebContentView.cpp
- cmake/InstallRules.cmake
- main.cpp
Always call platform_init after there's a QApplication, because in the installed configuration that's how we find the resources.
Try QCoreApplication::applicationDirPath() after looking in ./WebContent for the WebContent process. In an installed configuration, ladybird and WebContent will both be in $PREFIX/bin.
Add install rules for WebContent and its linked libraries, for if they ever differ from ladybird's.
> Ensure that installed ladybird can launch WebContent process properly

- cmake/FetchLagom.cmake
Recent Serenity changes put generated files for libraries in _deps/lagom-build/Userland/Libraries rather than lagom-build/Libraries.
> cmake: Add Userland/ subdirectories of Lagom binary dir to include path

- CMakeLists.txt
This pull request adds flags for ASAN, MSAN and UBSAN as well as configures gdb to follow forks, making debugging WebContent with `ninja debug` a bit nicer
> CMake: Some debugging improvements

- main.cpp
Let's ignore SIGINT if we're being debugged because GDB incorrectly forwards the signal to us even when it's set to "nopass". See https://sourceware.org/bugzilla/show_bug.cgi?id=9425 for details.
> Ignore SIGINT when we're being debugged

- Tab.cpp
- WebContentView.cpp
- WebContentView.h
We now emit a new signal for backward mouse button's mouseup and forward mouse button's mouseup which is handled by going back and forward in the history respectively:))
> Handle forward and backward mouse buttons

- Tab.cpp
- Tab.h
Previously we were always pushing to history on the on_load_start callback. Now we only do that if we are NOT navigating through the history navigation (loading pages by going back/forward). This is what the SerenityOS browser does:^)
> Don't push to history when loading through history navigation

- BrowserWindow.cpp
Steps to reproduce:
1. Open the Cookie Clicker game in a tab.
2. Open another website in another tab and make that the current tab.
3. Observe how the window's title mentions Cookie Clicker.
> Don't update the window title when a background tab changes its title

- Tab.cpp
The hackish initial loading of about:blank was previously added to the history, so you could go back to it (which wasn't very ergonomic). Now we set the m_is_history_navigation flag before loading it so it doesn't get added to the history.
> Don't add initial about:blank load to history

- WebContentView.cpp
- WebContentView.h
These were added for WebDriver, which doesn't have a Ladybird implementation yet.
Depends on https://github.com/SerenityOS/serenity/pull/15993 being merged first.
> Stub out new WebView::ViewImplementation APIs

- Tab.cpp
- WebContentView.cpp
- WebContentView.h
Previoulsy, reloading went back to the first page loaded by WebView::load() or WebView::load_html(), as they are the only methods that modify m_url, which is what the reload loaded. Now we handle reloads in Tab.cpp by simply loading the last entry in the m_history.
> Fix reloading functionality

- WebContentView.cpp
- WebContentView.h
These were added for WebDriver, which doesn't have a Ladybird implementation yet.
Depends on https://github.com/SerenityOS/serenity/pull/16031 being merged first.
> Stub out new cookie WebView::ViewImplementation APIs

- WebContentView.cpp
- WebContentView.h
These were added for WebDriver, which doesn't have a Ladybird implementation yet.
Depends on https://github.com/SerenityOS/serenity/pull/16033 being merged first.
> Stub out new history navigation WebView::ViewImplementation APIs

- WebContentView.cpp
Similar to https://github.com/SerenityOS/serenity/commit/9782660. Unlike Serenity's browser, this doesn't affect reloading the page, as Ladybird refers to the History object for reloading (which is updated already on page load). However, this URL is used for e.g. crash reporting, so let's update it here as well.
> Update WebContentView's stored URL when a page starts/finishes loading

- WebContentView.cpp
- WebContentView.h
This doesn't need to do anything yet, but will do once we start passing events to web content *before* they're passed to our GUI.
This implements the changes from https://github.com/SerenityOS/serenity/pull/16128 - please merge them together. :^)
> Add stub callback for notify_server_did_finish_handling_input_event

- Tab.cpp
- WebContentView.cpp
- WebContentView.h
We now replace the current history entry if the page-load has been caused because of a redirect. This makes it able to traverse the history if one of the entries redirects you, which previously caused an infinite history traversion loop.
Depends on https://github.com/SerenityOS/serenity/pull/16004
> Replace history entry if loading URL because of a redirect

- ConsoleWidget.cpp
Fix to build after JS::MarkupGenerator got converted to use new string type:
https://github.com/SerenityOS/serenity/commit/112b3f73429eff7a3b6947c7fb45c62a0e5c0727
> Fix to build with JS::MarkupGenerator converted to use new string type

- SQLServer/main.cpp
When Ladybird exits, SQLServer can get stuck spinning at 100% CPU after the socket connection is closed. This changes the client to quit the event loop when that disconnect happens to ensure that SQLServer is properly destroyed.
Depends on https://github.com/SerenityOS/serenity/pull/16401
> Quit SQLServer when its connected client exits

- CMakeLists.txt
- ConsoleGlobalObject.h
- ConsoleWidget.h
- DOMNodeProperties.h
- InspectorWidget.cpp
- InspectorWidget.h
- ModelTranslator.cpp
- ModelTranslator.h
- SettingsDialog.cpp
- SettingsDialog.h
- TimerQt.cpp
- WebContentView.cpp
- WebContentView.h
- WebSocketClientManagerLadybird.cpp
- WebSocketClientManagerLadybird.h
This has been broken for a while now, and even when it did work it was very limited compared to Browser. 
This PR re-implements the inspector with _most_ features from good o' Browser now supported, the main things missing is the box-model and inspecting from the context menu.
> Reimplement the DOM inspector :^) 
