BrowserWindow.cpp, BrowserWindow.h, WebView.cpp, WebView.h
This PR has a bug in that the icon is split in half not sure why.
=> Add Favicon to the window

README.md
Hi. I have added to the README.md the packages needed to compile this project on them and other derivatives.
=> Added Arch Linux/Manjaro required packages

WebView.cpp
You can now use IBeam, Hand and Arrow cursors in Ladybird!
=> Add basic cursor shape support in WebView

ConsoleClient.cpp, ConsoleGlobalObject.cpp, ConsoleGlobalObject.h, WebView.cpp
=> Update for LibJS realm changes

ConsoleClient.cpp, ConsoleGlobalObject.cpp, ConsoleGlobalObject.h, WebView.cpp
See:
- https://github.com/SerenityOS/serenity/commit/867ad03
- https://github.com/SerenityOS/serenity/commit/cfa5885
=> Update for LibJS global and console object changes

WebView.cpp
This is not a good solution, but it prevents some crashes.
=> Fix some crashes related to keyboard events

Tab.cpp
In such a way the UI matches what the user can do.
=> Tab: Conditionally enable back/forward buttons

README.md
=> Add instructions for building on Fedora

README.md
library path for easier reference and finding.
=> Add link to Serenity's LibWeb

CookieJar.cpp, RequestManagerQt.cpp
See https://github.com/SerenityOS/serenity/commit/4230dbbb21ec68cbb9844130d5e90276c96d16c2
=> Everywhere: Replace "protocol" with "scheme" url helpers

ConsoleClient.cpp
Requires https://github.com/SerenityOS/serenity/pull/15349
=> ConsoleClient: Get the current ESO from the new HostDefined helper

main.cpp
This makes opening test files much more ergonomic :^)
=> Accept file paths and domains in addition to URLs as an argument

WebContentView.cpp, WebContentView.h
The build was broken with the latest pull from serenity's repo, this fixes it
=> Stub out notify_server_did_request_fullscreen_window

Documentation/BuildInstructions.md, ladybird.nix
This adds nix/nixos building support like the Toolchain/serenity.nix in serenity.
Let me know if this needs any changes/is not needed :^))
=> Misc: Add ladybird.nix for nix support

BrowserWindow.cpp, BrowserWindow.h, CMakeLists.txt, Tab.cpp, Tab.h, WebContent/main.cpp, WebContentView.cpp, WebContentView.h, WebDriver/CMakeLists.txt, WebDriver/Session.cpp, WebDriver/Session.h, WebDriver/main.cpp, main.cpp
[Screencast from 2022-11-14 12-20-14.webm](https://user-images.githubusercontent.com/5600524/201725158-7b27a883-f7c5-400e-9a7f-910fc416590d.webm)
This depends on https://github.com/SerenityOS/serenity/pull/16066 being merged first.
=> Implement WebDriver for Ladybird :^)

BrowserWindow.cpp, WebContentView.cpp, WebContentView.h
[Screencast from 2022-11-14 17-23-04.webm](https://user-images.githubusercontent.com/5600524/201780741-dc75b081-7103-4238-a362-1d3fe2ff02a1.webm)
=> WebDriver: Implement the cookie endpoints for Ladybird

BrowserWindow.cpp
Based on SerenityOS/serenity#16072.
=> Add block pop-ups checkbox to debug menu

WebContentView.cpp, WebContentView.h
Depends on https://github.com/SerenityOS/serenity/pull/16091 being merged first.
[Screencast from 2022-11-16 10-55-46.webm](https://user-images.githubusercontent.com/5600524/202230195-3411c724-8740-4b3a-b959-fe440c72db4a.webm)
=> Implement updated alert/confirm/prompt IPC methods

WebContent/main.cpp, WebDriver/CMakeLists.txt, WebDriver/Session.cpp, WebDriver/Session.h, WebDriver/main.cpp
[Screencast from 2022-11-22 08-17-22.webm](https://user-images.githubusercontent.com/5600524/203324380-61123de6-1831-4b51-ac68-51c631537e6d.webm)
Depends on https://github.com/SerenityOS/serenity/pull/16145 being merged first.
=> WebDriver: Support running headless WebDriver sessions

AndroidPlatform.cpp, BrowserWindow.cpp, BrowserWindow.h, ConsoleClient.cpp, ConsoleClient.h, ConsoleWidget.cpp, ConsoleWidget.h, FontPluginQt.cpp, FontPluginQt.h, ModelTranslator.cpp, RequestManagerQt.cpp, RequestManagerQt.h, Settings.h, Tab.cpp, Tab.h, Utilities.cpp, Utilities.h, WebContent/main.cpp, WebContentView.cpp, WebContentView.h, WebDriver/Session.cpp, WebDriver/main.cpp, WebSocketClientManagerLadybird.cpp, WebSocketClientManagerLadybird.h, WebSocketImplQt.cpp, WebSocketImplQt.h, WebSocketLadybird.cpp, WebSocketLadybird.h, main.cpp
https://github.com/SerenityOS/serenity/pull/16311
=> Update for AK::{String => DeprecatedString} rename

WebContentView.cpp, WebContentView.h
Depends on https://github.com/SerenityOS/serenity/pull/16344
=> Pass small LibGfx structs by value

Documentation/BuildInstructions.md
Update build prerequisites on macOS to include CMake too :^)
=> Documentation: Add cmake to macOS dependencies

BrowserWindow.cpp, BrowserWindow.h, CMakeLists.txt, SQLServer/CMakeLists.txt, SQLServer/main.cpp, WebContentView.cpp, WebContentView.h, main.cpp
[Screencast from 2022-12-05 12-03-35.webm](https://user-images.githubusercontent.com/5600524/206222771-649c1e77-db2b-4229-a76c-2d8aceda73ad.webm)
Depends on https://github.com/SerenityOS/serenity/pull/16358 being merged first.
=> Store :cookie:s in a LibSQL database

SQLServer/main.cpp, main.cpp
Depends on: https://github.com/SerenityOS/serenity/pull/16403
[Screencast from 2022-12-09 15-32-49.webm](https://user-images.githubusercontent.com/5600524/206804042-ddbe7af3-64fd-4c22-a2ad-7424480dd0c2.webm)
=> Migrate SQLServer to be launched as a singleton process
